import { Injectable } from '@angular/core';

@Injectable()
export class FollowedDealService {

  constructor() { }

  getFollowedDealDetails(){
    return[
      {"_id":{"$oid":"5a6a5b7dab769ee4c7d39a7a"},"dealNumber":200,"companyLogo":"perspica.jpg","targetCompanyName":"Perspica","dealCode":"Panthers","transactionType":"ACQ","purchasePrice":"Undisclosed","publicrPriviate":"Private","dealType":"Product","marketSegment":"Software","sponsoringGroupName":"AppDynamics","groupDescription":"","pressAnnounceSource":"","companyDescription":"","Announce Year":"","Close Quarter":"","targetMarketSegment":"","monetizationModel":"","transactionStage":"Legal Close","empCountonAnnounce":"","employeesOnBoarded":"","":"","createdBy":"Admin","updatedBy":"Admin","createdAt":"1/25/2018","updatedAt":"1/25/2018"},
      {"_id":{"$oid":"5a6a5b7dab769ee4c7d39a82"},"dealNumber":199,"companyLogo":"ProjectLeap-TN-60x60.jpg","targetCompanyName":"Springpath","dealCode":"Leap","transactionType":"ACQ","purchasePrice":"$320M","publicrPriviate":"Private","dealType":"Product","marketSegment":"Data Center, Software","sponsoringGroupName":"CSP","groupDescription":"Computing Systems Product Group","pressAnnounceSource":"https://blogs.cisco.com/news/cisco-announces-data-center-news-%e2%80%8e","companyDescription":"Springpath, a leader in hyperconvergence software, has developed a next-generation distributed file system�purpose-built for hyperconverged infrastructure (HCI).","Announce Year":"FY18","Close Quarter":"Q1FY18","targetMarketSegment":"HyperConverged Infrastructure (HCI).","monetizationModel":"NA","transactionStage":"Announced","empCountonAnnounce":133,"employeesOnBoarded":125,"":"","createdBy":"Admin","updatedBy":"Admin","createdAt":"1/25/2018","updatedAt":"1/25/2018"},
      {"_id":{"$oid":"5a6a5b7eab769ee4c7d39a8a"},"dealNumber":198,"companyLogo":"Observable Networks.png","targetCompanyName":"Observable Networks","dealCode":"Oslo","transactionType":"ACQ","purchasePrice":"Undisclosed","publicrPriviate":"Private","dealType":"T\u0026T","marketSegment":"Security","sponsoringGroupName":"SBG","groupDescription":"Security Business Group","pressAnnounceSource":"https://blogs.cisco.com/news/cisco-announces-cloud-security-news","companyDescription":"Observable Networks provides cloud-native network forensics security applications delivered as a service. Observable Networks� technology is based on dynamic behavioral modeling of all devices on the network. Observable Networks� solutions provide security analysts with the ability to gain real-time situational awareness of all users, devices and traffic on the network, whether in the data center or the cloud. Together, Cisco and Observable Networks will extend our Stealthwatch solution into the cloud with highly scalable behavior analytics and comprehensive visibility.","Announce Year":2017,"Close Quarter":"Q4FY17","targetMarketSegment":"Security","monetizationModel":"4 - Software as a Service","transactionStage":"Legal Close","empCountonAnnounce":14,"employeesOnBoarded":"TBD","":"","createdBy":"Admin","updatedBy":"Admin","createdAt":"1/25/2018","updatedAt":"1/25/2018"},
      {"_id":{"$oid":"5a6a5b7eab769ee4c7d39a91"},"dealNumber":197,"companyLogo":"mindmeld.png","targetCompanyName":"MindMeld","dealCode":"Mojo","transactionType":"ACQ","purchasePrice":"$125M","publicrPriviate":"Private","dealType":"T\u0026T","marketSegment":"Web Services","sponsoringGroupName":"CCTG","groupDescription":"Cisco Cloud Technology Group","pressAnnounceSource":"https://newsroom.cisco.com/press-release-content?type=webcontent\u0026articleId=1841620","companyDescription":"MindMeld has pioneered the development of a unique AI platform that enables customers to build intelligent and human-like conversational interfaces for any application or device. Through its proprietary machine learning (ML) technology, MindMeld delivers incredible accuracy to help users interact with voice and chat assistants in a more natural way. Together, Cisco and MindMeld can bring voice AI to meeting rooms throughout the world, where Cisco's near-ubiquitous presence of video and telephony hardware will help increase adoption of AI technology across the workplace","Announce Year":2017,"Close Quarter":"Q4FY17","targetMarketSegment":"","monetizationModel":"NA","transactionStage":"Employees Onboarded","empCountonAnnounce":24,"employeesOnBoarded":22,"":"","createdBy":"Admin","updatedBy":"Admin","createdAt":"1/25/2018","updatedAt":"1/25/2018"}
    
        
    ];

  }
}
